### ISSUE TITLE
Storage documentation on AsyncCacheClient method.

### ISSUE THREAD

**Issue by Hemanth95** [karosis88/hishel#70]
Hey 
Great work on this package. I am trying to add storage to AsyncCacheClient, using the same documentation provided for CacheClient. It is giving this error:
`  File "/home/hkkrishna/workspace/madrid_portal_core/lib64/python3.11/site-packages/hishel/_async/_transports.py", line 80, in handle_async_request
    stored_data = await self._storage.retreive(key)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: object NoneType can't be used in 'await' expression`

It works well with CacheClient.

code: 
```
storage = hishel.FileStorage()
client = hishel.AsyncCacheClient(
            base_url=<endpoint>,
            trust_env=False,
            timeout=httpx.Timeout(20.0, connect=30.0),
            limits = limits,
            storage=storage,
        )
resp = await client.get(<url>)
```

**Comment by karosis88** [comment]
Hi! It's the first issue opened by a user, so I am very happy to see it!! :tada: 

You should simply change `httpcore.FileStorage` to `httpcore.AsyncFileStorage`, which is the relevant implementation that supports async/await syntax.

Like so:

```python
storage = hishel.AsyncFileStorage()
client = hishel.AsyncCacheClient(
            base_url=<endpoint>,
            trust_env=False,
            timeout=httpx.Timeout(20.0, connect=30.0),
            limits = limits,
            storage=storage,
        )
resp = await client.get(<url>)
```

I think asynchronous usage is poorly documented, so I will work on it. 
Thank you for this issue!

**Comment by Hemanth95** [comment]
Thank you very much. :)
